### ISSUE TITLE
IsCreditCardNumberValid does not work

### ISSUE THREAD

**Issue by intrueder** [Burbigo/KottansTest#2]
Seems that Luhn algorithm implementation is not correct
Test with `3566002020360505`, it should pass validation.

**Comment by Burbigo** [comment]
I can't reproduce the same error on my PC. My solution gives answer like on screen, for input data: "566002020360505"
Could you please provide more information as and when there is the answer you
![2016-05-07](https://cloud.githubusercontent.com/assets/17294530/15091849/5b0207d6-145f-11e6-8cda-62550855df27.png)
