### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [Burbigo/KottansTest#4]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
Such number should not pass validation, but it passes.

**Comment by Burbigo** [comment]
**fix issue #4.**
>Now card number is valid or has vendor, only if it has vendor and pass Luhn algorithm; Also I'm checking input data, and show some warnings if input number doesn't meet to requirements. If number wasn't valid and u generate next number, You'll see warning about "Check card number" or warning like "no more card for this vendor", if next number doesn't owned to current vendor

**Comment by intrueder** [comment]
Still reproducable.
Note: code has been checked by unit tests. And this issue is related to method `IsCreditCardNumberValid`, so, if the code has any check in some other place, it can not be checked. Please, provide fix for `IsCreditCardNumberValid` method.

**Comment by Burbigo** [comment]
I understood where was my mistake, and i think I corrected it.
False or True it's result of validation, when you're pressed the button "Check card number"
![untitled](https://cloud.githubusercontent.com/assets/17294530/15207243/68c6ed42-182d-11e6-894a-27de9f92adf6.png)
