### ISSUE TITLE
GenerateNextCreditCardNumber hangs on some inputs

### ISSUE THREAD

**Issue by intrueder** [Burbigo/KottansTest#6]
Pass the number `"349999999999991"` into method `GenerateNextCreditCardNumber`
Expected result: exception or some message like "no more card numbers available for this vendor"
Actual result: application hangs (infinite loop)

**Comment by Burbigo** [comment]
I'm sorry, I understand that time is over, but want to finish this task, just for myself.
Thats why i have question: "why do i've to show message like ``"no more card numbers available for this vendor"``, if I can take the next valid number for AmericanExpress ``"370000000000002"``?"

**Comment by intrueder** [comment]
Good point, but coding this way leads us to handle range overflow for each vendor and maybe in different way. It's much harder than just result with error message. Maybe message is not clear, so we can just say `"no more cards available for this range"`

**Comment by Burbigo** [comment]
I agree, and consider these rectification)
